name: three-gen-vqa
channels:
  - defaults
  - conda-forge
  - nvidia

dependencies:
  - python=3.11
  - cuda-toolkit=12.4.0
  - cudnn=9.3
  - gcc=13.2
  - gxx=13.2
  - pip
  - pip:
      - -r requirements.txt
