[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "t2v_metrics"
version = "1.0.0"
description = "Evaluating Text-to-Visual Generation with Image-to-Text Generation."
authors = [
    {name="Zhiqiu Lin", email="zl279@cornell.edu"},
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]

dependencies = [
    "huggingface-hub>=0.21.0",
    "numpy==1.26.4",
    "open-clip-torch==2.30.0",
    "opencv-python==4.11.0.86",
    "pandas==2.2.3",
    "scipy==1.15.1",
    "torch==2.5.1",
    "sentencepiece==0.2.0",
    "transformers==4.51.3",
    "omegaconf==2.3.0",
    "iopath==0.1.10",
    "fairscale==0.4.13",
    "tiktoken==0.8.0",
    "turbot5==0.0.1",
    "einops==0.8.0",
    "flash-attn==2.7.3",
    "auto-gptq==0.7.1",
    "accelerate==1.3.0",
    "regex==2024.11.6",
    "ftfy==6.3.1",
    "gdown==5.2.0",
    "optimum==1.24.0",
    "protobuf==5.29.3",
    "bitsandbytes==0.45.1",
    "xformers==0.0.28.post3"
]

[tool.setuptools]
include-package-data = true
packages = ["t2v_metrics"]

[tool.setuptools.package-data]
't2v_metrics' = ['**/*.json', '**/*.yaml', '**/*.py']

[project.urls]
Home = "https://linzhiqiu.github.io/papers/vqascore"